[book]
title = "Rust 実践パターン & エンジニアリングノウハウ"
authors = ["Rust Training Team"]
language = "ja"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/microsoft/RustTraining"
default-theme = "light"
preferred-dark-theme = "ayu"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.playground]
editable = true
line-numbers = true
